2020-03-14 21:30:25.320508: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /ssoft/spack/paien/v2/opt/spack/linux-rhel7-x86_E5v2_Mellanox_GPU/gcc-6.4.0/openblas-0.2.20-2pegluj6ooc6a43nj4omvn5xjnytdbqd/lib:/ssoft/spack/paien/v2/opt/spack/linux-rhel7-x86_E5v2_Mellanox_GPU/gcc-6.4.0/mvapich2-2.3rc2-pmnkf53th5qa4e3c6bosai4h3qixbkjw/lib:/ssoft/spack/paien/v2/opt/spack/linux-rhel7-x86_E5v2_Mellanox_GPU/gcc-6.4.0/cudnn-6.0-ttykxkxslnycryvzr5gm6ptsh2spz3mv/lib64:/ssoft/spack/paien/v2/opt/spack/linux-rhel7-x86_E5v2_Mellanox_GPU/gcc-6.4.0/cuda-9.1.85-qrb6dpbuhogia6oonjhj7du6afxdnkvr/lib64:/ssoft/spack/paien/v2/opt/spack/linux-rhel7-x86_E5v2_Mellanox_GPU/gcc-4.8.5/gcc-6.4.0-erlrzwzfyblwgmlyyi2tzqziveaazowy/lib64:/ssoft/spack/paien/v2/opt/spack/linux-rhel7-x86_E5v2_Mellanox_GPU/gcc-4.8.5/gcc-6.4.0-erlrzwzfyblwgmlyyi2tzqziveaazowy/lib
2020-03-14 21:30:25.320777: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /ssoft/spack/paien/v2/opt/spack/linux-rhel7-x86_E5v2_Mellanox_GPU/gcc-6.4.0/openblas-0.2.20-2pegluj6ooc6a43nj4omvn5xjnytdbqd/lib:/ssoft/spack/paien/v2/opt/spack/linux-rhel7-x86_E5v2_Mellanox_GPU/gcc-6.4.0/mvapich2-2.3rc2-pmnkf53th5qa4e3c6bosai4h3qixbkjw/lib:/ssoft/spack/paien/v2/opt/spack/linux-rhel7-x86_E5v2_Mellanox_GPU/gcc-6.4.0/cudnn-6.0-ttykxkxslnycryvzr5gm6ptsh2spz3mv/lib64:/ssoft/spack/paien/v2/opt/spack/linux-rhel7-x86_E5v2_Mellanox_GPU/gcc-6.4.0/cuda-9.1.85-qrb6dpbuhogia6oonjhj7du6afxdnkvr/lib64:/ssoft/spack/paien/v2/opt/spack/linux-rhel7-x86_E5v2_Mellanox_GPU/gcc-4.8.5/gcc-6.4.0-erlrzwzfyblwgmlyyi2tzqziveaazowy/lib64:/ssoft/spack/paien/v2/opt/spack/linux-rhel7-x86_E5v2_Mellanox_GPU/gcc-4.8.5/gcc-6.4.0-erlrzwzfyblwgmlyyi2tzqziveaazowy/lib
2020-03-14 21:30:25.320795: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Using TensorFlow backend.
COMET INFO: Experiment is live on comet.ml https://www.comet.ml/kjappelbaum/color-ml/5f163824084e45d6a0df429df8c174d6

Traceback (most recent call last):
  File "/home/kjablonk/anaconda3/envs/colorml/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kjablonk/anaconda3/envs/colorml/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/scratch/kjablonk/colorml/colorml/colorml/run_training.py", line 124, in <module>
    main()
  File "/home/kjablonk/anaconda3/envs/colorml/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kjablonk/anaconda3/envs/colorml/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kjablonk/anaconda3/envs/colorml/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kjablonk/anaconda3/envs/colorml/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/scratch/kjablonk/colorml/colorml/colorml/run_training.py", line 120, in main
    orchestrate(config)
  File "/scratch/kjablonk/colorml/colorml/colorml/run_training.py", line 31, in orchestrate
    make_if_not_exists(config["outpath"])
  File "/scratch/kjablonk/colorml/colorml/colorml/utils.py", line 183, in make_if_not_exists
    os.makedirs(path)
  File "/home/kjablonk/anaconda3/envs/colorml/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/kjablonk/anaconda3/envs/colorml/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/kjablonk/anaconda3/envs/colorml/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 4 more times]
  File "/home/kjablonk/anaconda3/envs/colorml/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users'
COMET INFO: ----------------------------
COMET INFO: Comet.ml Experiment Summary:
COMET INFO:   Data:
COMET INFO:     url: https://www.comet.ml/kjappelbaum/color-ml/5f163824084e45d6a0df429df8c174d6
COMET INFO:   Uploads:
COMET INFO:     git-patch: 1
COMET INFO: ----------------------------
COMET INFO: Uploading stats to Comet before program termination (may take several seconds)
COMET INFO: Waiting for completion of the file uploads (may take several seconds)
COMET INFO: Still uploading
srun: error: r02-node01: task 0: Exited with exit code 1
srun: Terminating job step 8097026.0
